### ISSUE TITLE
关于容器依赖的一个问题

### ISSUE THREAD

**Issue by mia0x75** [1Panel-dev/appstore#1388]
假设 redis 已经安装且正常运行，那么我在一个新的 docker-compose.yml 如何引用呢？最终效果就是多个容器共用了这个 redis 容器。

我用下面写法，好像部署起来有些问题

```
services:
  broker:
    extends:
      file: ../../redis/redis/docker-compose.yml
      service: redis

  webserver:
    image: someone/some-app:version
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - ${PANEL_APP_PORT_HTTP}:8000
    volumes:
      - ./data/data:/data
    environment:
      REDIS: redis://broker:6379
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
```
