### ISSUE TITLE
1panel面板中官方应用商店中的[7.4.1] Redis，一键安装存在问题

### ISSUE THREAD

**Issue by huanglian666** [1Panel-dev/appstore#2451]
# 问题描述
一键安装Redis警告
```shell
WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
```

#解决方案
官方应用商店中的docker-compose文件中新增配置选项
```yaml
services:
  redis:
    sysctls:
      - net.core.somaxconn=512
```
#期待
希望官方可以把这个配置加入到官方应用商店的默认配置选项中，期待官方采纳！！！！
