### ISSUE TITLE
添加 webp

### ISSUE THREAD

**Issue by Anyexyz** [1Panel-dev/appstore#325]
官方博客上曾发布一篇[《优雅的让 Halo 支持 webp 图片输出》](https://halo.run/archives/halo-and-webp)，这篇文章很好的解决了Halo上附件图片太大的问题，提高了加载性能。
研究[官方文档](https://github.com/webp-sh/webp_server_go)后发现其支持docker部署，故进行尝试后确认其可行性。

**Comment by Anyexyz** [comment]
docker-compose.yml编写参考
```yml
version: '3'

services:
  webp:
    image: webpsh/webp-server-go
    # image: ghcr.io/webp-sh/webp_server_go
    restart: always
    environment:
      - MALLOC_ARENA_MAX=1
      # - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
      # - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4.5.6
    volumes:
      - /opt/1panel/apps/halo/halo/data/attachments:/opt/pics # 上传图片目录，此处为1panel部署的halo的上传目录
      - /opt/1panel/apps/halo/halo/data/attachments/upload:/opt/exhaust # 缓存目录，此处为1panel部署的halo的上传目录
      - ./config.json:/etc/config.json
    ports:
      -  127.0.0.1:3333:3333
    deploy:
      resources:
        limits:
          memory: 400M
    memswap_limit: 400M
```
